### ISSUE TITLE
error when running on multiple scaffolds

### ISSUE THREAD

**Issue by mariels** [petrelharp/local_pca#12]
Hello,

I am running local PCA on either one scaffold or all the large scaffolds (>10M bp) of my whole genome data. 
For each scaffold run individually, the program runs fine and I get all the results including the PCA of the extracted corners.
When I use a bcf including all the large scaffolds, the different steps are running fine until making the PCA plots from the extracted corners.

I get the following error message with a windows of 100 SNPs:
#Warning in sweep(f(k), 2, colm, "-"): STATS is longer than the extent of 'dim(x)
#[MARGIN]'
#Error in array(STATS, dims[perm]): 'dims' cannot be of length 0

Or this error with windows of 1000 SNPs
#Taking input= as a system command ('bcftools query -f '[ %GT]\n' -r MRVK01000135.1:19528169-20462752 NA') and a variable has been used in the expression passed to `input=`. Please use fread(cmd=...). There is a security concern if you are creating an app, and the app could have a malicious user, and the app is not running in a secure environment; e.g. the app is running as root. Please read item 5 in the NEWS file for v1.11.6 for more information and for the option to suppress this message.
#Error in colMeans(x, na.rm = TRUE): 'x' must be an array of at least two dimensions

I have attached the results in pdf.

Could you please help on how I could resolve it?

Many thanks,

Marie

[all_scaffolds_100SNPs.pdf](https://github.com/petrelharp/local_pca/files/4468942/all_scaffolds_100SNPs.pdf)
[all_scaffolds_1000SNPs.pdf](https://github.com/petrelharp/local_pca/files/4468944/all_scaffolds_1000SNPs.pdf)

**Comment by TeresaPegan** [comment]
I am also getting this exact same error (the one you get with the 100 SNP windows), along with the warning about input=. I don't have a solution, but just wanted to second the question about how to troubleshoot it!

**Comment by petrelharp** [comment]
Whoops, sorry! This initial bug arrived at a rather hectic time. I'll have a look.

**Comment by petrelharp** [comment]
Hm, let's see. @mariels, did you resolve this issue?

It sounds like there's a matrix whose dimension gets dropped because of not enough rows or columns, somewhere. To debug this, I would start by stepping through the code in an interactive session, and either running `traceback()` afterwards, or executing `options (error=recover)` beforehand. This should let you check that things are making sense as you go along, and tell you the line in the code where the error occurred.

I could help debug if you post the code you are using? I might need access to the data somehow also.

**Comment by TeresaPegan** [comment]
Hi,
I think this is happening because all of my chromosomes were in the same bcf file.

Stepping through the "summarize_run.Rmd" script in the "templated" folder, the error arises at line 202. (All of the previous lines are working for me). The full message R gives me is:
```
Taking input= as a system command ('bcftools query -f '[ %GT]\n' -r 5:206-54702 NA') and a variable has been used in the expression passed to `input=`. Please use fread(cmd=...). There is a security concern if you are creating an app, and the app could have a malicious user, and the app is not running in a secure environment; e.g. the app is running as root. Please read item 5 in the NEWS file for v1.11.6 for more information and for the option to suppress this message.
[E::hts_open_format] Failed to open file "NA" : No such file or directory
Failed to read from NA: No such file or directory
Error in colMeans(x, na.rm = TRUE) : 
  'x' must be an array of at least two dimensions
```
It seems like something is up with qfun. 

I tried making qfun by hand with the code from the multi_vcf_query_fn function. 
```
# input the function needs:
chrom.list=chroms; file=bcf.files; regions=reg 
# the function first defines "chroms"
chroms <- unlist(chrom.list)
chroms
 [1]  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20
# looks ok
# next it makes "files"
files <- file[rep(seq_along(chrom.list), sapply(chrom.list, 
        length))]
files
 X6Sept_high_cauch_demo_300_all 
"/Users/tmpegan/local_pca-master/templated/data/6Sept_high_cauch_demo_300/6Sept_high_cauch_demo_300_all.bcf" 
                                                                                                        <NA> 
                                                                                                          NA 
                                                                                                        <NA> 
                                                                                                          NA 
                                                                                                        <NA> 
                                                                                                          NA 
                                                                                                        <NA> 
                                                                                                          NA 
                                                                                                        <NA> 
                                                                                                          NA 
                                                                                                        <NA> 
                                                                                                          NA 
                                                                                                        <NA> 
                                                                                                          NA 
                                                                                                        <NA> 
                                                                                                          NA 
                                                                                                        <NA> 
                                                                                                          NA 
                                                                                                        <NA> 
                                                                                                          NA 
                                                                                                        <NA> 
                                                                                                          NA 
                                                                                                        <NA> 
                                                                                                          NA 
                                                                                                        <NA> 
                                                                                                          NA 
                                                                                                        <NA> 
                                                                                                          NA 
                                                                                                        <NA> 
                                                                                                          NA 
                                                                                                        <NA> 
                                                                                                          NA 
                                                                                                        <NA> 
                                                                                                          NA 
                                                                                                        <NA> 
                                                                                                          NA 


# scroll right to see all the NAs
```

The output of this little piece of the code, "rep(seq_along(chrom.list), sapply(chrom.list,length))", is the numbers 1 through 19 (for my 19 chromosomes). But bcf.files, the object (as "file") that multi_vcf_query_fn is trying to subset using 1 through 19 as indices, is just this:
```
bcf.files
                                                                              X6Sept_high_cauch_demo_300_all 
"/Users/tmpegan/local_pca-master/templated/data/6Sept_high_cauch_demo_300/6Sept_high_cauch_demo_300_all.bcf" 
```

All my chromosomes are in the same bcf. I don't know for sure that all of the NAs in the "files" object made by multi_vcf_query_fn are what's causing this error (I'm not sure what to try next for debugging), but it certainly seems like this part of the script is designed to take each chromosome as its own bcf. (Maybe the whole thing was designed that way - the example in the "templated" section on Github says):
```
# Finding PCs for data/chr1.bcf and writing out to lostruct_results/type_snp_size_20_weights_none_jobid_589131/chr1.pca.csv and lostruct_results/type_snp_size_20_weights_none_jobid_589131/chr1.regions.csv 
# Finding PCs for data/chr2.bcf and writing out to lostruct_results/type_snp_size_20_weights_none_jobid_589131/chr2.pca.csv and lostruct_results/type_snp_size_20_weights_none_jobid_589131/chr2.regions.csv 
```

I guess run_lostruct.R and the first part of this Rmd can handle all of the chromosomes being on the same bcf fine, but maybe not the PCA made with the corners?

I tried using individual bcf's for each chromosome as the input, and the whole script including the corner PCA plot worked for me as expected. So, splitting up a bcf into multiple files, one per chromosome or scaffold, is one way of getting around this problem (although I'm not sure how convenient that is for a scaffold-level genome like the one of @mariels -- I've used non-model-organism genomes with 150,000+ scaffolds before!)

**Comment by petrelharp** [comment]
Ok, thanks, @TeresaPegan - this is perfect. Let's see: you're right, the NAs are coming because we're indexing `files` by indices that are bigger than its length (to check that's what happens: `(1:10)[12]` returns `NA`).  Let's see. The documentation says that:
```
 chrom.list A list of character vectors of chromosome names, the \code{n}th saying which chromosomes are available in the \code{n}th vcf file.
 file The name(s) of the indexed vcf file(s).
```
What are `chrom.list` and `file` as you are calling them? You could post the `config.json` instead.

And - I've just pushed a minor update to `multi_vcf_query_fn` that gives more informative error messages in this situation...

**Comment by TeresaPegan** [comment]
Here are chrom.list and file:
```
chrom.list
 [1]  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20
> file
                                                                              X6Sept_high_cauch_demo_300_all 
"/Users/tmpegan/local_pca-master/templated/data/6Sept_high_cauch_demo_300/6Sept_high_cauch_demo_300_all.bcf" 
>
```

It looks like I can't attach a json, but here is the text of it. 
```
{
  "input_dir": ["data/6Sept_high_cauch_demo_300"],
  "sample_info": ["/Users/tmpegan/local_pca-master/templated/data/6Sept_high_cauch_demo_300/6Sept_high_cauch_demo_300_sample_info.tsv"],
  "type": ["snp"],
  "size": [100],
  "npc": [2],
  "nmds": [2],
  "missing": [0],
  "subsample": [1],
  "jobid": ["319115"],
  "help": [false],
  "outdir": ["lostruct_results/type_snp_size_100_weights_none_jobid_319115"],
  "start.time": ["2020-09-06 16:28:43"],
  "run.dir": ["/Users/tmpegan/local_pca-master/templated"],
  "weights": [1],
  "bcf_files": ["/Users/tmpegan/local_pca-master/templated/data/6Sept_high_cauch_demo_300/6Sept_high_cauch_demo_300_all.bcf"],
  "bcf_file_names": ["X6Sept_high_cauch_demo_300_all"]
}
```

Thank you!

**Comment by petrelharp** [comment]
*(Here's some talking through of what's going on:)*  Well, I think that `chrom.list` should be `list(2:20)` instead of `2:20` (i.e., a list of length one, whose single entry is the vector of chromosome names).  Hm, and how is that set: well, [here](https://github.com/petrelharp/local_pca/blob/a5eb7bfe0dd5cbcff39ff34e29f1909a8aacdb75/templated/summarize_run.Rmd#L201) it's `chroms`, which is set [earlier](https://github.com/petrelharp/local_pca/blob/a5eb7bfe0dd5cbcff39ff34e29f1909a8aacdb75/templated/summarize_run.Rmd#L96) to be the unique entries of the `chrom` columns of the `regions.files`, which is just all the [.regions.csv](https://github.com/petrelharp/local_pca/blob/a5eb7bfe0dd5cbcff39ff34e29f1909a8aacdb75/templated/summarize_run.Rmd#L87) files in this directory. And ok, the `file` argument is [`bcf.files`](https://github.com/petrelharp/local_pca/blob/a5eb7bfe0dd5cbcff39ff34e29f1909a8aacdb75/templated/summarize_run.Rmd#L201), which comes in from the json. This was confusing because [earlier](https://github.com/petrelharp/local_pca/blob/a5eb7bfe0dd5cbcff39ff34e29f1909a8aacdb75/templated/summarize_run.Rmd#L58) a different variable named `chroms` was defined to be `bcf_file_names` from the json. Oh! And, the json file is produced by [run_lostruct.R](https://github.com/petrelharp/local_pca/blob/a5eb7bfe0dd5cbcff39ff34e29f1909a8aacdb75/templated/run_lostruct.R#L84), using the names of the bcf files.

So, I've assumed that there's one bcf per chromosome, and that they've got the same names as the chromosomes themselves.  (*Edit:* it looks like the names of the files don't have to match the names of the chromosomes, at least.*) Whoops! That's a bug. A quick fix for you is to put your bcf files in that format. But the fix to `run_lostruct.R` shouldn't be too bad - if I put up a possible fix, would you be able to test it?

**Comment by TeresaPegan** [comment]
Yes, I can test a fix!
