### ISSUE TITLE
The effect of sample number and relationship on local PCA results

### ISSUE THREAD

**Issue by Axolotl233** [petrelharp/local_pca#19]
Hi

recently I used method 'local Pca' to detect potential haplotype region in our SNP data, The program ran normal and find some outliers. 

But I wonder if sample number of different popluation and relationship between sample will cause deviation on the result. Our data include two popluation, one have 40 samples and another have 17 samples, and relationship between some samples is very close.If you could kindly provide me some advice or code, I will be appreciate.

Thanks

**Comment by petrelharp** [comment]
Hello! Good question - it might? My guess is that it won't, since there isn't a big difference between 40 and 17, but if you want to explore, you can adjust the "weights" by providing a [weight file](https://github.com/petrelharp/local_pca/blob/master/templated/run_lostruct.R#L27) to the templated run or by passing weights to the `w` parameter of `eigen_windows( )`, as for instance [here](https://github.com/petrelharp/local_pca/blob/master/templated/run_lostruct.R#L148). We did this for the medicago data we analyzed [here](https://github.com/petrelharp/local_pca/blob/be16ac033937a5180e55f0caab463b6ef463883e/medicago/data/make-weights.R).

I'm going to close this issue, but please re-open if you discover any problems.
