### ISSUE TITLE
Error in `colnames<-`(`*tmp*`, value = out.colnames) 

### ISSUE THREAD

**Issue by Lin-Yuying** [petrelharp/local_pca#29]
Hi there,

I am using lostruct and the test data `https://github.com/petrelharp/local_pca/blob/master/lostruct/tests/testthat/test.bcf` from `https://github.com/petrelharp/local_pca/tree/master/lostruct/tests/testthat` 

The codes I used are
```
bcf.file <- 'test.bcf'
sites <- vcf_positions(bcf.file)
win.fn.snp <- vcf_windower(bcf.file, size=100, type="snp", sites=sites) 
snp.pca <- eigen_windows(win.fn.snp,k=2)
```

I got error messages as following, do you know what happened? I tried to look into that, and suspect this error is probably due to [line 77 - 78 of the script `https://github.com/petrelharp/local_pca/blob/master/lostruct/R/eigen_windows.R`](https://github.com/petrelharp/local_pca/blob/master/lostruct/R/eigen_windows.R#L77). However I still have no idea what exactly happened.
```
Error in `colnames<-`(`*tmp*`, value = out.colnames) : 
  attempt to set 'colnames' on an object with less than two dimensions
```

Thanks in advance!

Best,
Y. L.

**Comment by petrelharp** [comment]
Thanks for the very nice report, @Lin-Yuying. Let's see - that looks like a plausible place for the error... but, with some experimenting, I'm not sure if `do.call(rbind, ...)` will ever return something that isn't two-dimensional? There should be more output that gives a traceback? For instance, you could call `traceback()` after getting the error, and paste the output here, or even do `options(error=recover)` and get an interactive debugging browser. So - if it *is* in that location, then in the debugging browser you could see what `eigen.mat` looks like, and that should tell us where the problem lies.

One question: are there less than 100 snps in the dataset?

**Comment by Lin-Yuying** [comment]
Thanks for your quick reply. Indeed, I assumed there are more than 100 SNPs in the test data set. However, there are not. Now, I changes window size from 100 to 10. It works. 

I think I am gonna close this. 

Thanks again! 

Best,
Y. L.

**Comment by petrelharp** [comment]
Thanks! But, perhaps I'll fix this up so that it at least returns a more informative error.

**Comment by petrelharp** [comment]
Done! Thanks again!
