### ISSUE TITLE
run_lostruct.R error 

### ISSUE THREAD

**Issue by RCLynch414** [petrelharp/local_pca#31]
Hi, I have local_pca installed and the main functions  (popres_example.R) running without error. I'm getting stuck on an error in templated script though, which would be very useful for the more detailed outputs: 

templated % Rscript run_lostruct.R -t snp -s 20 -i joined_data -I joined_data/sample_info.tsv
Finding PCs for chromsome chr1 in file /Users/ryan/local_pca-master/templated/joined_data/all_chrs.bcf and writing out to lostruct_results/type_snp_size_20_weights_none_jobid_269154/chr1.pca.csv and lostruct_results/type_snp_size_20_weights_none_jobid_269154/chr1.regions.csv 
Error in n < 1 || n > max(chrom.breaks) : 
  'length = 49' in coercion to 'logical(1)'
Calls: <Anonymous> -> <Anonymous>
In addition: Warning messages:
1: In any(chrom.wins) : coercing argument of type 'double' to logical
2: In vcf_windower_snp(file = file, sites = sites, size = size, samples = samples) :
  Trimming from chromosome ends: 1: 14 SNPs.
Execution halted

I get the same error with -i templated/data

Thanks

**Comment by petrelharp** [comment]
Ah-ha: this is due to a [change in R's behavior](https://cran.r-project.org/doc/manuals/r-devel/NEWS.html)
![Screenshot from 2023-06-13 21-31-06](https://github.com/petrelharp/local_pca/assets/1046249/1a08544c-3517-4e58-b881-70fac4a227f9)
... it should be an easy fix; I'll get on it (and you could workaround by using an earlier version of R).

**Comment by petrelharp** [comment]
Done! If you re-install, it should work.

**Comment by RCLynch414** [comment]
Thank you!
