### ISSUE TITLE
Error generating PCs of corners

### ISSUE THREAD

**Issue by jkreinz** [petrelharp/local_pca#34]
Hi Peter!

Back running lostruct on some new data. I'm going off the medicago example and at the step of generating PCs from the corners. I run ` corner.pcs <- eigen_windows( data=corner.winfn,  k=2, do.windows=1:ncol(mds.corners), mc.cores=10)`  but am getting an error (pasted below) and i'm not sure why. Thanks in advance for your help!

Error in dimnames(x) <- dn :
  length of 'dimnames' [2] not equal to array extent)

**Comment by petrelharp** [comment]
Hello, Julia!

Hm - that's not enough to track it down - could you paste in more (all?) of the output?

**Comment by jkreinz** [comment]
Yep! That was actually pretty much all of the error message but I can give some more context. Everything was smooth up until this point and I was able to generate all the MDS plots. 

<img width="696" alt="Screenshot 2024-04-09 at 5 20 35 PM" src="https://github.com/petrelharp/local_pca/assets/15037621/0d2a846d-d9dd-4672-8794-176452325aa8">

Then I proceeded to the next steps, running: 

```
>  dim(as.matrix(MDS[,1:2]))
[1] 9186    2
mincirc <- enclosing_circle( as.matrix(MDS[,1:2] ))
mds.corners <- corners( as.matrix(MDS[,1:2]), prop=.05 )
> dim(mds.corners)
[1] 460   3
corner.winfn <- function (n) { win.fn.snp( mds.corners[,n] ) }
```

which produced the error: 
Error in dimnames(x) <- dn :
  length of 'dimnames' [2] not equal to array extent
In addition: Warning message:
In parallel::mclapply(..., mc.cores = mc.cores) :
  all scheduled cores encountered errors in user code

Let me know if there is something else that would be useful to share & thanks Peter!

**Comment by petrelharp** [comment]
How about the output of `traceback()` after you get the error?

**Comment by jkreinz** [comment]
```
> traceback()
3: `colnames<-`(`*tmp*`, value = out.colnames)
2: eigen_windows_winfn(win.fn = data, do.windows = do.windows, k = k,
       w = w, mc.cores = mc.cores, ...)
1: eigen_windows(data = corner.winfn, mc.cores = 20, k = 2, do.windows = 1:ncol(mds.corners))
```

**Comment by petrelharp** [comment]
Well, this sort of thing usually happens when there's a lot of missing data somewhere, causing something to be not the shape we expect.  But, it might totally be a bug in the medicago example code.

I'm having trouble digging into it more because I don't have the medicago data handy any more. I think you might have more luck if you followed the example in `templated/` rather than `medicago/`; that's what people (eg me) usually use, while the medicago example was more to document what's in the paper? But, I'd like to see what's going on, so if there's an easy way to send me the data (and the code you ran), I'd track it down.

**Comment by jkreinz** [comment]
Thanks Peter. Going off the templated example worked for me so I must have been doing something funny. Appreciate your help!

Julia

**Comment by petrelharp** [comment]
Glad to hear it! I'll close this, then.
